AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  finetwork-contacts

  Sample SAM Template for finetwork-contacts

Globals:
  Function:
    Timeout: 3

Resources:
  # Define the IAM role with AmazonDynamoDBFullAccess policy
  HttpCrudVeroRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: http-crud-vero-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::211125561005:policy/service-role/AWSLambdaBasicExecutionRole-cf6e6895-1e95-4f00-bbaa-d5b22ae36dea
        - arn:aws:iam::211125561005:policy/service-role/AWSLambdaMicroserviceExecutionRole-c7cc56ce-1c55-47ab-baa0-103c5bb1a663

  ContactsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/contacts
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: !GetAtt HttpCrudVeroRole.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ContactsDynamoTable  
      Events:
        GetAllContacts:
          Type: HttpApi
          Properties:
            Path: /contacts
            Method: GET
        GetAnContact:
          Type: HttpApi
          Properties:
            Path: /contacts/{pk}
            Method: GET
        GetContactByNIF:
          Type: HttpApi
          Properties:
            Path: /contacts/identificationdocument/{NIF}
            Method: GET 
        GetContactByPhone:
          Type: HttpApi
          Properties:
            Path: /contacts/phone/{MSISDN}
            Method: GET 
        DeleteAnContact:
          Type: HttpApi
          Properties:
            Path: /contacts/{pk}
            Method: DELETE
        UpdateContact:
          Type: HttpApi
          Properties:
            Path: /contacts
            Method: PUT
        CreateContact:
          Type: HttpApi
          Properties:
            Path: /contacts/lead/create
            Method: POST   
  ContactsDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Test_lambda_vero
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: nif
          AttributeType: S
        - AttributeName: phone
          AttributeType: S
        - AttributeName: mail
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: NIFIndex
          KeySchema:
            - AttributeName: nif
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: PhoneIndex
          KeySchema:
            - AttributeName: phone
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: MailIndex
          KeySchema:
            - AttributeName: mail
              KeyType: HASH
          Projection:
            ProjectionType: ALL
Outputs:
  ApiEndpoint:
    Description: "The invoke URL for our HTTP API"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/contacts"
  Function:
    Description: "DynamoDB handler function ARN"
    Value: !GetAtt ContactsFunction.Arn
